---
### Service Web Personal ####
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-personal-dev
    ports:
      - "8085:4321"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./astro.config.mjs:/app/astro.config.mjs
      - ./tailwind.config.mjs:/app/tailwind.config.mjs
      - ./uno.config.ts:/app/uno.config.ts
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./nginx:/app/nginx
    command: npx astro dev --host
    networks:
      - private

networks:
  private:
    external: true
