---
### Service Web Personal ####
services:
  app:
    image: web-personal:10
    container_name: web-personal
    ports:
      - "8085:80"
    restart: unless-stopped
    # Si necesitas variables de entorno
    environment:
      - NODE_ENV=production
    # Si necesitas healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 31s
      timeout: 10s
      retries: 4
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    labels:
      - "server.environment=${ENV:-dev}"
      - "server.network=public"
      - "server.description=Web Personal de kobouharriet.site"
      - "server.project=briefcase"
      - "server.monitoring.enabled=true"
    networks:
      - public
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "192.168.0.13:24224"
        tag: "docker.web-personal"
        fluentd-async: "true"

networks:
  public:
    external: true
