---
### Service Web Personal ####
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-personal
    ports:
      - "8080:8080"
    restart: unless-stopped
    # Si necesitas variables de entorno
    environment:
      - NODE_ENV=production
    # Si necesitas healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - home

networks:
  home:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
