"""Utilidades compartidas por los render_graphviz.py de cada modelo.

Existe por una razón concreta: la salida de `dot` incluye un comentario con la
versión de Graphviz que la generó.

    <!-- Generated by graphviz version 15.1.0 (20260618.0150)
     -->

Ese banner cambia con cada actualización de Graphviz aunque la geometría del
diagrama sea idéntica byte a byte. Con los SVG versionados en el repo, eso
significa diffs espurios al reexportar desde otra máquina, y un chequeo de
drift en CI que falla por la versión del runner en vez de por el modelo.

Se lo elimina en el único lugar por donde pasan todos los renders.
"""

import os
import re
import subprocess
from pathlib import Path

# El comentario abarca dos líneas: la versión y el cierre indentado.
_BANNER = re.compile(
    r"<!-- Generated by graphviz version [^\n]*\n -->\n",
)

# public/architecture/, relativo a esta carpeta. `ARCH_OUT` la redirige a un
# directorio temporal: es como check_drift.py renderiza sin pisar lo versionado.
OUT = Path(os.environ.get("ARCH_OUT") or Path(__file__).parent.parent / "public" / "architecture")


def write_svg(target: Path, dot_source: str) -> None:
    """Renderiza `dot_source` con Graphviz y lo escribe sin el banner de versión."""
    svg = subprocess.run(
        ["dot", "-Tsvg"],
        input=dot_source,
        text=True,
        check=True,
        capture_output=True,
    ).stdout

    svg, n = _BANNER.subn("", svg)
    # Si Graphviz cambia el formato del comentario, el banner vuelve a filtrarse
    # a los archivos versionados sin que nada falle. Preferimos enterarnos acá.
    if n != 1:
        raise RuntimeError(
            f"Se esperaba exactamente 1 banner de versión de Graphviz, se encontraron {n}. "
            "Cambió el formato de salida de `dot`: revisar _BANNER en architecture/_render.py."
        )

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(svg)

    # Con ARCH_OUT el destino cae fuera del repo y relative_to() explotaría.
    repo = Path(__file__).parent.parent
    shown = target.relative_to(repo) if target.is_relative_to(repo) else target.name
    print(f"  {shown}")
